apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-bot
spec:
  selector:
    matchLabels:
      app: library-bot
  replicas: 1
  template:
    metadata:
      labels:
        app: library-bot
    spec:
      containers:
      - name: library-bot
        image: okteto.dev/library-bot:latest
